version: 0.0
os: linux 
# files section executes in INSTALL step.
files:
  - source: backend/
    destination: /
  - source: dist/
    destination: /usr/share/nginx/html/
  - source: files/
    destination: /etc/nginx/nginx.conf
file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/application_stop
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
