name: Install AWS CLI
description: Action of Installing AWS CLI

runs:
  using: "composite"
  steps:
    - name: Install AWS CLI
      shell: bash
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
